### ISSUE TITLE
why it hints "Found 0 blog posts to generate."?

### ISSUE THREAD

**Issue by briteming** [ByteBakersCo/babilema#15]
hi.

i forked ur repo here: https://github.com/briteming/babilema/ ,and created a issue: https://github.com/briteming/babilema/issues/1 ,

and on windows's git-bash.exe ,i installed babilema, then,

12799@DESKTOP-B6LK9IO MINGW64 ~ (main)$ export GITHUB_TOKEN="value of my GITHUB_TOKEN" && export GITHUB_REPOSITORY="briteming/babilema" && babilema -config ~/.babilema.toml
2025/01/29 13:28:06 Config loaded successfully from C:/Users/12799/.babilema.toml
2025/01/29 13:28:06 History file not found, a new one will be created on update.
2025/01/29 13:28:06 Found 0 blog posts to generate.
12799@DESKTOP-B6LK9IO MINGW64 ~ (main)$ 

but i did create an issue https://github.com/briteming/babilema/issues/1 , why it hints "Found 0 blog posts to generate."?
thank u for ur reply!

12799@DESKTOP-B6LK9IO MINGW64 ~ (main)$ cat ~/.babilema.toml
website_url = "https://briteming.github.io/babilema"
blog_title = "Babilema: A Minimalist Static Blog Generator"
12799@DESKTOP-B6LK9IO MINGW64 ~ (main)$

**Comment by zyriab** [comment]
Hey!

Could you share your config? (`.babilema.toml` by default)

There should be the following key `blog_post_issue_prefix` in it.
By default, its value is `[BLOG]`, meaning that your issue must start with `[BLOG]` for it to be detected by Babilema.
So, in your case, the name should be `[BLOG] 测试`.

Feel free to use any key you'd like, of course :)

Once that's done, try re-running Babilema and it should be good!

**Comment by briteming** [comment]
hi.

```
12799@DESKTOP-B6LK9IO MINGW64 ~ (main)$ export GITHUB_TOKEN="value of my GITHUB_TOKEN" && export GITHUB_REPOSITORY="briteming/babilema" && babilema -config ~/.babilema.toml
2025/01/29 15:04:05 Config loaded successfully from C:/Users/12799/.babilema.toml
2025/01/29 15:04:05 History file not found, a new one will be created on update.
2025/01/29 15:04:05 Found 1 blog posts to generate.
2025/01/29 15:04:05 History file updated.
2025/01/29 15:04:05 Error generating blog posts: open C:\Users\12799\go\bin\templates\post.html: The system cannot find the path specified.

12799@DESKTOP-B6LK9IO MINGW64 ~ (main)$ ls go/bin/
babilema.exe*        http-file-server.exe*  moul.exe*     tmp/
dotweb-example.exe*  mdblog-by-sb.exe*      p2pfile.exe*
foto.exe*            mdblog.exe*            tinypng.exe*

12799@DESKTOP-B6LK9IO MINGW64 ~ (main)
$
```

there is no templates in ~/go/bin/,what to do?
thanks

**Comment by zyriab** [comment]
Indeed, it's not supposed to look into `~/go/bin` afaik...

Before we dive into this, did you write a HTML template post?
Maybe you could try cloning the [demo branch](https://github.com/ByteBakersCo/babilema/tree/blog).
Re-reading the docs, it's not very clear that a HTML template is needed, apologies, I haven't used Babilema in almost a year.

If the demo branch does not work:

I just edited your reply to format the code (put 3 backticks [`] around your code to format it nicely btw).
That's an interesting issue, might be a Windows thing, I haven't used Babilema on Windows and don't have a Windows machine nearby to test it so I can't say for sure.

Could you try to copy `babilema.exe` in your project root and run it directly like so

```sh
./babilema -config ~/.babilema.toml
```

Alternatively, you could change the config and specify the absolute paths (or use `~`, it might work), something like:

```toml
output_dir = "C:/Users/12799"                 # The directory where the generated html files will be saved
temp_dir = "C:/Users/12799/tmp"                 # The directory where the temporary files will be saved
template_post_file_path = "C:/Users/12799/templates/post.html"
template_header_file_path = "C:/Users/12799/templates/header.html"
template_footer_file_path = "C:/Users/12799/templates/footer.html"
template_index_file_path = "C:/Users/12799/templates/index.html" # Your blog's homepage file
css_dir = "C:/Users/12799/templates/css" # The directory where the CSS files are stored (if any)
```
